# build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ./CmsLiteWebAppClient/ ./CmsLiteWebAppClient/
WORKDIR /src/CmsLiteWebAppClient
RUN dotnet publish -c Release -o /out

# run
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .
ENV ASPNETCORE_URLS=http://+:9090
EXPOSE 9090
ENTRYPOINT ["dotnet", "CmsLiteWebAppClient.dll"]