name: cmslite-dev
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite --blobHost 0.0.0.0"
    volumes: ["azurite:/data"]

  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.api
    environment:
      AzureStorage__ConnectionString: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;"
      AzureStorage__Container: "cms"
      Database__Path: "/data/cms.sqlite"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      # JWT Configuration for Development
      Jwt__Key: "development-jwt-secret-key-for-cmslite-container-32-chars-minimum"
      Jwt__Issuer: "CmsLiteDev"
      Jwt__Audience: "CmsLiteDevUsers"
      Jwt__ValidateIssuer: "false"
      Jwt__ValidateAudience: "false"
      Jwt__ValidateLifetime: "true"
      Jwt__ValidateIssuerSigningKey: "true"
    depends_on:
      - azurite
    volumes:
      - ./data:/data

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.web
    depends_on:
      - api

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx-dev
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - web

volumes:
  azurite: