version: "3.9"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite --blobHost 0.0.0.0"
    ports: [ "10000:10000" ]
    volumes: [ "azurite:/data" ]

  api:
    build:
      context: ..
      dockerfile: ./Dockerfile
    environment:
      AzureStorage__ConnectionString: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFeq...==;BlobEndpoint=http://azurite:10000/devstoreaccount1;"
      AzureStorage__Container: "cms"
      Database__Path: "/data/cms.sqlite"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports: [ "8080:8080" ]
    depends_on: [ azurite ]
    volumes:
      - api_data:/data
volumes:
  azurite:
  api_data: